version: "3.8"
services:
  ui:
    container_name: fwks-app-ui
    build:
      dockerfile: docker/dockerfile_ui
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "25000:80"
    volumes:
      - ./docker/config/ui_nginx.conf:/etc/nginx/conf.d/default.conf
  api:
    container_name: fwks-app-api
    build:
      dockerfile: docker/dockerfile_api
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - docker/config/api.env
    ports:
      - "25001:80"
networks:
  default:
    external: true
    name: sandbox
